### ISSUE TITLE
Display tagged pictures

### ISSUE THREAD

**Issue by kiempoturner** [fortybytes/instagram-laravel#3]
Hi, your wrapper is working well thanks for that, may i know how to display tagged pictures using the api's endpoint? thanks

**Comment by sumardi** [comment]
Hi @kiempoturner

Try this,

``` php
$tag = Instagram::getTag('hashtag');
$tag->getMedia();

// or you can pass an array of parameters to getMedia().
$tag->getMedia(
    array('count' => 3)
);
```

**Comment by kiempoturner** [comment]
do i need to put this anywhere? = https://api.instagram.com/v1/tags/nofilter?access_token=ACCESS-TOKEN

**Comment by sumardi** [comment]
Just follow this [instruction to authenticate user](https://github.com/fortybytes/instagram-laravel#authentication).

**Comment by kiempoturner** [comment]
hey ive used this code:

public function getMedia() {
    $tag = Instagram::getTag('poster');
    $tag->getMedia();
    }

and this route:

Route::get('media', 'HomeController@getMedia');

but i got this error:

"Call to undefined method Instagram\Auth::getTag()"

```
    switch (count($args))
    {
        case 0:
            return $instance->$method();

        case 1:
            return $instance->$method($args[0]);
```

Help me please.

**Comment by sumardi** [comment]
User need to authenticate first before calling that `getTag()` method.

**Comment by kiempoturner** [comment]
<h3>Hi, everything is working fine, i var_dump it and its working but im a bit blurry on displaying the media.</h3>

<h4>How do I display the grabbed media? </h4><br>

<i>This is my Controller :</i>

![3](https://f.cloud.github.com/assets/6310473/2510646/8f1eb314-b40a-11e3-8374-e17052195fa8.PNG)

<i>This is my Route :</i>

![2](https://f.cloud.github.com/assets/6310473/2510645/8f1e1d78-b40a-11e3-9161-0592aca13b0e.PNG)

<i>This is my user.blade.php :</i>

![1](https://f.cloud.github.com/assets/6310473/2510644/8f1cfe98-b40a-11e3-9eaf-fa98a2f75446.PNG)

<i>This is what i get on browser</i>

![4](https://f.cloud.github.com/assets/6310473/2510669/d20673f6-b40a-11e3-8a25-5b4554fb86b4.PNG)

**Comment by kiempoturner** [comment]
<h2>Hi, everything is okay now.</h2>

<i>I used this code to display the tagged media:</i>

```
public function getTagged()
{   

    $tag = Instagram::getTag('snow');
    $tagged = $tag->getMedia();


    foreach($tagged as $photo){

        echo "<img src=\"".$photo->images->low_resolution->url."\">";

    }
```

THANKS!

**Comment by narangrishab** [comment]
@kiempoturner Hello. Could you post the entire controller code for Instagram? I need to learn how to import images from a specific tag. Do I need to have authentication functions?
