### ISSUE TITLE
Having trouble with Logout 

### ISSUE THREAD

**Issue by kiempoturner** [fortybytes/instagram-laravel#4]
Hi,

I dont quite understand the logout part. It logged the user out and redirecting user to the home page. And when i click login again, it refresh the page and Get the logged out user's session back. Help please.

Thank you.

**Comment by sumardi** [comment]
Logging out user is [documented here](https://github.com/fortybytes/instagram-laravel#authentication). Just clear the session.

``` php
public function getLogout()
{
    Session::forget(Config::get('instagram::session_name'));

    return Redirect::to('/');
}
```

**Comment by kiempoturner** [comment]
But then it refreshes the previous users' access token if i click login again. Im trying to login using different user. thanks
