### ISSUE TITLE
Call to undefined method Instagram\Instagram::getAccessToken()

### ISSUE THREAD

**Issue by andrewdavidkay** [fortybytes/instagram-laravel#6]
I get a Call to undefined method Instagram\Instagram::getAccessToken() exception thrown if I try to access Instagram::getCurrentUser() within the getAuthorize() UserController method. 

``` php
public function getAuthorize() {

        Session::put(Config::get('instagram::session_name'), Instagram::getAccessToken(Input::get('code')));

        $user = Instagram::getCurrentUser();

        return Redirect::to('/');
}
```

**Comment by sumardi** [comment]
You cannot call `Instagram::getCurrentUser()` in the `getAuthorize()` method. It won't work that way. You can only call the method after it been redirected to another page.
