### ISSUE TITLE
Call to undefined method...

### ISSUE THREAD

**Issue by Asored-D** [fortybytes/instagram-laravel#8]
Hi! When i try to use your variables in the view i get the following:

Code for example:
<?php 
$user = Instagram::getCurrentUser(); 
echo $user 
?>

Result:
Call to undefined method Instagram\Auth::getCurrentUser() 

The login with instagram is working wonderful...would be very great if you can help me to solve this issue ;)

Greetings!

**Comment by sumardi** [comment]
@drosa88 make sure you store access token in the session and redirect before make API calls.

``` php
Session::put(Config::get('instagram::session_name'), Instagram::getAccessToken(Input::get('code')));
Redirect::to('/');
```
